default['nc_base'].tap do |ncb|
  ncb['base_ver']    = '8.1.0'
  ncb['point_ver']   = "#{node['nc_base']['base_ver']}.1"
  ncb['fp_ver']      = '25'
  ncb['fp_pkg']      = "#{node['nc_base']['base_ver']}-TIV-OMNIbusCore-linux-x86_64-FP00#{node['nc_base']['fp_ver']}.zip"
  ncb['fp_rel']      = '5.50.96.20210309_2049'
  ncb['package']     = "OMNIbus-v#{node['nc_base']['point_ver']}-Core.linux64.zip"
  ncb['im_ver']      = '1.9.1005.20210309_1755'
  ncb['im_pkg']      = "agent.installer.linux.gtk.x86_64_#{node['nc_base']['im_ver']}.zip"
  ncb['prs']         = '1.2.0.18-Tivoli-PRS-Unix-fp0001.tar'
  ncb['prs_patch']   = 'netcool-prs-IV93620.tar.gz'
  ncb['app_dir']     = '/apps'
  ncb['nc_dir']      = "#{node['nc_base']['app_dir']}/netcool"
  ncb['ob_dir']      = "#{node['nc_base']['nc_dir']}/omnibus"
  ncb['media_dir']   = "#{node['nc_base']['app_dir']}/media"
  ncb['install_dir'] = "#{node['nc_base']['media_dir']}/nco81"
  ncb['fp_dir']      = "#{node['nc_base']['media_dir']}/nco81fp"
  ncb['gate_dir']    = "#{node['nc_base']['media_dir']}/gateways"
  ncb['nckl_dir']    = "#{node['nc_base']['media_dir']}/nckl"
  ncb['temp_dir']    = '/tmp'
  ncb['prs_dir']     = '/tmp/prs'
  ncb['im_dir']      = '/tmp/im'
  ncb['media_url']   = 'http://10.1.1.30/media'
  ncb['rhel']        = %w(bc ntp firefox unzip)
  ncb['rhel_x11']    = %w(bc ntp firefox compat-libstdc++-33.i686 libXtst.i686 compat-libstdc++-33 compat-db libXp libXmu libXtst pam libXft gtk2 xauth motif xclock)
  ncb['nc_act']      = 'netcool'
  ncb['nc_grp']      = 'ncoadmin'
  ncb['nc_pwd']      = 'P@ssw0rd'
  ncb['nc_epwd']     = '$1$xaVDw1NS$NmyxP1YTnqenTM8LmEO2f.'
  ncb['prs_codes']   = %w(DSH ESS FAS FRS NCM NOA NOC NOD NOP NOS NOW NPA ODP PAD PAM PAW TCR TIP)
end
